### ISSUE TITLE
Recents Thumbnails 

### ISSUE THREAD

**Issue by libnidsj** [libnidsj/patchrom_angler#1]
System isn't saving any thumbnail if you press home and then go to recents menu. 

Initial workaround : set old miui Recents menu.

**Comment by GuaiYiHu** [comment]
maybe this commit will help you. 
https://git.oschina.net/guaiyihu/patchrom_miui8_xiaomi_leo/commit/1a247088786a799887c1f56f98d132264564a220

**Comment by libnidsj** [comment]
Thanks, got it fixed.
@GuaiYiHu I will not cherry pick your commit cause cant fetch from oschina, but will give you the credits when commiting.

**Comment by libnidsj** [comment]
Fixed with commit #20364b2
